// components/features-planet.tsx
import Image from "next/image";
import PlanetImg from "@/public/images/planet.png";
import PlanetOverlayImg from "@/public/images/planet-overlay.svg";
import PlanetTagImg01 from "@/public/images/planet-tag-01.png";
import PlanetTagImg02 from "@/public/images/planet-tag-02.png";
import PlanetTagImg03 from "@/public/images/planet-tag-03.png";
import PlanetTagImg04 from "@/public/images/planet-tag-04.png";

export default function FeaturesPlanet() {
  return (
    <section className="relative before:absolute before:inset-0 before:-z-20 before:bg-gray-900">
      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        <div className="py-12 md:py-20">
          {/* Section header */}
          <div className="mx-auto max-w-3xl pb-16 text-center md:pb-20">
            <h2 className="text-3xl font-bold text-gray-200 md:text-4xl">
              AI + 运营系统：核心能力
            </h2>
            <p className="mt-4 text-lg text-gray-400">
              用自动化与 AI 把“重复劳动”变成“可控流程”，把“经验”变成“可复用能力”。
            </p>
          </div>
          {/* Planet */}
          <div className="pb-16 md:pb-20" data-aos="zoom-y-out">
            <div className="text-center">
              <div className="relative inline-flex rounded-full before:absolute before:inset-0 before:-z-10 before:scale-[.85] before:animate-[pulse_4s_cubic-bezier(.4,0,.6,1)_infinite] before:bg-linear-to-b before:from-blue-900 before:to-sky-700/50 before:blur-3xl after:absolute after:inset-0 after:rounded-[inherit] after:[background:radial-gradient(closest-side,var(--color-blue-500),transparent)]">
                <Image
                  className="rounded-full bg-gray-900"
                  src={PlanetImg}
                  width={400}
                  height={400}
                  alt="Planet"
                />
                <div className="pointer-events-none" aria-hidden="true">
                  <Image
                    className="absolute -right-64 -top-20 z-10 max-w-none"
                    src={PlanetOverlayImg}
                    width={789}
                    height={755}
                    alt="Planet decoration"
                  />
                  <div>
                    <Image
                      className="absolute -left-28 top-16 z-10 animate-[float_4s_ease-in-out_infinite_both] opacity-80 transition-opacity duration-500"
                      src={PlanetTagImg01}
                      width={253}
                      height={56}
                      alt="Tag 01"
                    />
                    <Image
                      className="absolute left-56 top-7 z-10 animate-[float_4s_ease-in-out_infinite_1s_both] opacity-30 transition-opacity duration-500"
                      src={PlanetTagImg02}
                      width={241}
                      height={56}
                      alt="Tag 02"
                    />
                    <Image
                      className="absolute -left-20 bottom-24 z-10 animate-[float_4s_ease-in-out_infinite_2s_both] opacity-25 transition-opacity duration-500"
                      src={PlanetTagImg03}
                      width={243}
                      height={56}
                      alt="Tag 03"
                    />
                    <Image
                      className="absolute bottom-32 left-64 z-10 animate-[float_4s_ease-in-out_infinite_3s_both] opacity-80 transition-opacity duration-500"
                      src={PlanetTagImg04}
                      width={251}
                      height={56}
                      alt="Tag 04"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* Grid */}
          <div className="grid overflow-hidden sm:grid-cols-2 lg:grid-cols-3 *:relative *:p-6 *:before:absolute *:before:bg-gray-800 *:before:[block-size:100vh] *:before:[inline-size:1px] *:before:[inset-block-start:0] *:before:[inset-inline-start:-1px] *:after:absolute *:after:bg-gray-800 *:after:[block-size:1px] *:after:[inline-size:100vw] *:after:[inset-block-start:-1px] *:after:[inset-inline-start:0] md:*:p-10">
            <article>
              <h3 className="mb-2 flex items-center space-x-2 font-medium text-gray-200">
                <svg
                  className="fill-blue-500"
                  xmlns="http://www.w3.org/2000/svg"
                  width={16}
                  height={16}
                >
                  <path d="M2 4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V4Zm2-4a4 4 0 0 0-4 4v8a4 4 0 0 0 4 4h8a4 4 0 0 0 4-4V4a4 4 0 0 0-4-4H4Zm1 10a1 1 0 1 0 0 2h6a1 1 0 1 0 0-2H5Z" />
                </svg>
                <span>机器人与工作区管理</span>
              </h3>
              <p className="text-[15px] text-gray-400">
                统一管理 Bot、权限与环境配置，让多团队协作更安全、更清晰。
              </p>
            </article>
            <article>
              <h3 className="mb-2 flex items-center space-x-2 font-medium text-gray-200">
                <svg
                  className="fill-blue-500"
                  xmlns="http://www.w3.org/2000/svg"
                  width={16}
                  height={16}
                >
                  <path d="M14.29 2.614a1 1 0 0 0-1.58-1.228L6.407 9.492l-3.199-3.2a1 1 0 1 0-1.414 1.415l4 4a1 1 0 0 0 1.496-.093l7-9ZM1 14a1 1 0 1 0 0 2h14a1 1 0 1 0 0-2H1Z" />
                </svg>
                <span>AI 智能回复</span>
              </h3>
              <p className="text-[15px] text-gray-400">
                关键词 + 模板 + AI 生成三段式组合，覆盖高频问题并保持口径一致。
              </p>
            </article>
            <article>
              <h3 className="mb-2 flex items-center space-x-2 font-medium text-gray-200">
                <svg
                  className="fill-blue-500"
                  xmlns="http://www.w3.org/2000/svg"
                  width={16}
                  height={16}
                >
                  <path
                    d="M2.248 6.285a1 1 0 0 1-1.916-.57A8.014 8.014 0 0 1 5.715.332a1 1 0 0 1 .57 1.916 6.014 6.014 0 0 0-4.037 4.037Z"
                    opacity=".3"
                  />
                  <path d="M8 11a3 3 0 1 1 0-6 3 3 0 0 1 0 6Zm0-2a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm1.715-6.752a1 1 0 0 1 .57-1.916 8.014 8.014 0 0 1 5.383 5.383 1 1 0 1 1-1.916.57 6.014 6.014 0 0 0-4.037-4.037Zm4.037 7.467a1 1 0 1 1 1.916.57 8.014 8.014 0 0 1-5.383 5.383 1 1 0 1 1-.57-1.916 6.014 6.014 0 0 0 4.037-4.037Zm-7.467 4.037a1 1 0 1 1-.57 1.916 8.014 8.014 0 0 1-5.383-5.383 1 1 0 1 1 1.916-.57 6.014 6.014 0 0 0 4.037 4.037Z" />
                </svg>
                <span>群组治理与反垃圾</span>
              </h3>
              <p className="text-[15px] text-gray-400">
                验证、限速、规则与审核组合，降低广告与刷屏，保障社区秩序。
              </p>
            </article>
            <article>
              <h3 className="mb-2 flex items-center space-x-2 font-medium text-gray-200">
                <svg
                  className="fill-blue-500"
                  xmlns="http://www.w3.org/2000/svg"
                  width={16}
                  height={16}
                >
                  <path d="M8 0a1 1 0 0 1 1 1v14a1 1 0 1 1-2 0V1a1 1 0 0 1 1-1Zm6 3a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h1a1 1 0 1 1 0 2h-1a3 3 0 0 1-3-3V4a3 3 0 0 1 3-3h1a1 1 0 1 1 0 2h-1ZM1 1a1 1 0 0 0 0 2h1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 1 0 0 2h1a3 3 0 0 0 3-3V4a3 3 0 0 0-3-3H1Z" />
                </svg>
                <span>频道内容排期</span>
              </h3>
              <p className="text-[15px] text-gray-400">
                定时发布与素材管理，节奏化输出内容，并支持效果追踪（按可用性）。
              </p>
            </article>
            <article>
              <h3 className="mb-2 flex items-center space-x-2 font-medium text-gray-200">
                <svg
                  className="fill-blue-500"
                  xmlns="http://www.w3.org/2000/svg"
                  width={16}
                  height={16}
                >
                  <path d="M10.284.33a1 1 0 1 0-.574 1.917 6.049 6.049 0 0 1 2.417 1.395A1 1 0 0 0 13.5 2.188 8.034 8.034 0 0 0 10.284.33ZM6.288 2.248A1 1 0 0 0 5.718.33 8.036 8.036 0 0 0 2.5 2.187a1 1 0 0 0 1.372 1.455 6.036 6.036 0 0 1 2.415-1.395ZM1.42 5.401a1 1 0 0 1 .742 1.204 6.025 6.025 0 0 0 0 2.79 1 1 0 0 1-1.946.462 8.026 8.026 0 0 1 0-3.714A1 1 0 0 1 1.421 5.4Zm2.452 6.957A1 1 0 0 0 2.5 13.812a8.036 8.036 0 0 0 3.216 1.857 1 1 0 0 0 .574-1.916 6.044 6.044 0 0 1-2.417-1.395Zm9.668.04a1 1 0 0 1-.041 1.414 8.033 8.033 0 0 1-3.217 1.857 1 1 0 1 1-.571-1.917 6.035 6.035 0 0 0 2.415-1.395 1 1 0 0 1 1.414.042Zm2.242-6.255a1 1 0 1 0-1.946.462 6.03 6.03 0 0 1 0 2.79 1 1 0 1 0 1.946.462 8.022 8.022 0 0 0 0-3.714Z" />
                </svg>
                <span>批量触达与分发</span>
              </h3>
              <p className="text-[15px] text-gray-400">
                通过模板与策略化触达群组/频道，控制频率与范围，避免打扰。
              </p>
            </article>
            <article>
              <h3 className="mb-2 flex items-center space-x-2 font-medium text-gray-200">
                <svg
                  className="fill-blue-500"
                  xmlns="http://www.w3.org/2000/svg"
                  width={16}
                  height={16}
                >
                  <path d="M9 1a1 1 0 1 0-2 0v6a1 1 0 0 0 2 0V1ZM4.572 3.08a1 1 0 0 0-1.144-1.64A7.987 7.987 0 0 0 0 8a8 8 0 0 0 16 0c0-2.72-1.36-5.117-3.428-6.56a1 1 0 1 0-1.144 1.64A5.987 5.987 0 0 1 14 8 6 6 0 1 1 2 8a5.987 5.987 0 0 1 2.572-4.92Z" />
                </svg>
                <span>数据复盘与洞察</span>
              </h3>
              <p className="text-[15px] text-gray-400">
                汇总关键指标、对话热点与风险事件，帮助团队快速定位问题与机会。
              </p>
            </article>
          </div>
        </div>
      </div>
    </section>
  );
}

// components/FeaturesPlanet.vue
<template>
<section
      class="relative overflow-hidden bg-gradient-to-b from-gray-50 via-blue-50/40 to-gray-50 before:pointer-events-none before:absolute before:inset-0 before:-z-10 before:bg-[radial-gradient(ellipse_90%_50%_at_50%_-5%,rgb(59_130_246/0.08),transparent_55%)]"
    >
      <div class="relative z-10 mx-auto max-w-6xl px-4 sm:px-6">
        <div class="py-12 md:py-20">
<div class="mx-auto max-w-3xl pb-16 text-center md:pb-20">
            <h2 class="text-3xl font-bold text-gray-900 md:text-4xl">
              AI + 运营系统：核心能力
            </h2>
            <p class="mt-4 text-lg text-gray-600">
              用自动化与 AI 把“重复劳动”变成“可控流程”，把“经验”变成“可复用能力”。
            </p>
          </div>
<div class="pb-16 md:pb-20" data-aos="zoom-y-out">
            <div class="text-center">
              <div class="relative mx-auto inline-flex items-center justify-center">
                <!-- 外圈：大范围柔光，弱化边界 -->
                <div
                  class="pointer-events-none absolute inset-[-18%] -z-10 animate-[pulse_5s_cubic-bezier(0.4,0,0.6,1)_infinite] rounded-full bg-blue-400/25 blur-[80px]"
                  aria-hidden="true"
                />
                <div
                  class="pointer-events-none absolute inset-[-8%] -z-10 rounded-full bg-gradient-to-b from-sky-200/50 via-blue-100/30 to-transparent blur-2xl"
                  aria-hidden="true"
                />
                <!-- 浅色区上的球体：偏亮蓝，与灰底协调 -->
                <div
                  class="relative aspect-square w-[min(88vw,380px)] shrink-0 overflow-hidden rounded-full bg-gradient-to-br from-sky-300 via-blue-500 to-indigo-700 shadow-[0_28px_70px_-20px_rgba(37,99,235,0.35)] ring-1 ring-white/40"
                  role="img"
                  aria-label="产品能力示意"
                >
                  <div
                    class="pointer-events-none absolute -left-[22%] -top-[22%] h-[72%] w-[72%] rounded-full bg-[radial-gradient(circle_at_center,rgb(255_255_255/0.45),transparent_58%)]"
                    aria-hidden="true"
                  />
                  <div
                    class="pointer-events-none absolute inset-[22%] rounded-full bg-[radial-gradient(circle_at_72%_78%,rgb(30_58_138/0.35),transparent_55%)]"
                    aria-hidden="true"
                  />
                  <div
                    class="pointer-events-none absolute inset-[6%] rounded-full border border-white/25"
                    aria-hidden="true"
                  />
                </div>
                <div class="pointer-events-none" aria-hidden="true">
                  <div
                    class="absolute -left-20 top-12 z-20 animate-[float_4s_ease-in-out_infinite_both] rounded-full border border-gray-200/90 bg-white/90 px-3 py-1.5 text-xs font-medium text-gray-800 shadow-md shadow-gray-900/5 backdrop-blur-sm sm:-left-24 sm:top-14"
                  >
                    开放集成
                  </div>
                  <div
                    class="absolute left-40 top-4 z-20 animate-[float_4s_ease-in-out_infinite_1s_both] rounded-full border border-gray-200/80 bg-white/85 px-3 py-1.5 text-xs font-medium text-gray-700 shadow-sm backdrop-blur-sm sm:left-52 sm:top-6"
                  >
                    Webhook
                  </div>
                  <div
                    class="absolute -left-14 bottom-16 z-20 animate-[float_4s_ease-in-out_infinite_2s_both] rounded-full border border-gray-200/80 bg-white/85 px-3 py-1.5 text-xs text-gray-700 shadow-sm backdrop-blur-sm sm:-left-20 sm:bottom-20"
                  >
                    API
                  </div>
                  <div
                    class="absolute bottom-24 left-48 z-20 animate-[float_4s_ease-in-out_infinite_3s_both] rounded-full border border-gray-200/90 bg-white/90 px-3 py-1.5 text-xs font-medium text-gray-800 shadow-md shadow-gray-900/5 backdrop-blur-sm sm:bottom-28 sm:left-56"
                  >
                    自动化
                  </div>
                </div>
              </div>
            </div>
          </div>
<div class="grid overflow-hidden rounded-2xl border border-gray-200/80 bg-white/60 shadow-sm shadow-gray-900/5 backdrop-blur-sm sm:grid-cols-2 lg:grid-cols-3 *:relative *:p-6 *:before:absolute *:before:bg-gray-200 *:before:[block-size:100vh] *:before:[inline-size:1px] *:before:[inset-block-start:0] *:before:[inset-inline-start:-1px] *:after:absolute *:after:bg-gray-200 *:after:[block-size:1px] *:after:[inline-size:100vw] *:after:[inset-block-start:-1px] *:after:[inset-inline-start:0] md:*:p-10">
            <article>
              <h3 class="mb-2 flex items-center space-x-2 font-medium text-gray-900">
                <svg
                  class="fill-blue-500"
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                >
                  <path d="M2 4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V4Zm2-4a4 4 0 0 0-4 4v8a4 4 0 0 0 4 4h8a4 4 0 0 0 4-4V4a4 4 0 0 0-4-4H4Zm1 10a1 1 0 1 0 0 2h6a1 1 0 1 0 0-2H5Z" />
                </svg>
                <span>机器人与工作区管理</span>
              </h3>
              <p class="text-[15px] text-gray-600">
                统一管理 Bot、权限与环境配置，让多团队协作更安全、更清晰。
              </p>
            </article>
            <article>
              <h3 class="mb-2 flex items-center space-x-2 font-medium text-gray-900">
                <svg
                  class="fill-blue-500"
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                >
                  <path d="M14.29 2.614a1 1 0 0 0-1.58-1.228L6.407 9.492l-3.199-3.2a1 1 0 1 0-1.414 1.415l4 4a1 1 0 0 0 1.496-.093l7-9ZM1 14a1 1 0 1 0 0 2h14a1 1 0 1 0 0-2H1Z" />
                </svg>
                <span>AI 智能回复</span>
              </h3>
              <p class="text-[15px] text-gray-600">
                关键词 + 模板 + AI 生成三段式组合，覆盖高频问题并保持口径一致。
              </p>
            </article>
            <article>
              <h3 class="mb-2 flex items-center space-x-2 font-medium text-gray-900">
                <svg
                  class="fill-blue-500"
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                >
                  <path
                    d="M2.248 6.285a1 1 0 0 1-1.916-.57A8.014 8.014 0 0 1 5.715.332a1 1 0 0 1 .57 1.916 6.014 6.014 0 0 0-4.037 4.037Z"
                    opacity=".3"
                  />
                  <path d="M8 11a3 3 0 1 1 0-6 3 3 0 0 1 0 6Zm0-2a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm1.715-6.752a1 1 0 0 1 .57-1.916 8.014 8.014 0 0 1 5.383 5.383 1 1 0 1 1-1.916.57 6.014 6.014 0 0 0-4.037-4.037Zm4.037 7.467a1 1 0 1 1 1.916.57 8.014 8.014 0 0 1-5.383 5.383 1 1 0 1 1-.57-1.916 6.014 6.014 0 0 0 4.037-4.037Zm-7.467 4.037a1 1 0 1 1-.57 1.916 8.014 8.014 0 0 1-5.383-5.383 1 1 0 1 1 1.916-.57 6.014 6.014 0 0 0 4.037 4.037Z" />
                </svg>
                <span>群组治理与反垃圾</span>
              </h3>
              <p class="text-[15px] text-gray-600">
                验证、限速、规则与审核组合，降低广告与刷屏，保障社区秩序。
              </p>
            </article>
            <article>
              <h3 class="mb-2 flex items-center space-x-2 font-medium text-gray-900">
                <svg
                  class="fill-blue-500"
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                >
                  <path d="M8 0a1 1 0 0 1 1 1v14a1 1 0 1 1-2 0V1a1 1 0 0 1 1-1Zm6 3a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h1a1 1 0 1 1 0 2h-1a3 3 0 0 1-3-3V4a3 3 0 0 1 3-3h1a1 1 0 1 1 0 2h-1ZM1 1a1 1 0 0 0 0 2h1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 1 0 0 2h1a3 3 0 0 0 3-3V4a3 3 0 0 0-3-3H1Z" />
                </svg>
                <span>频道内容排期</span>
              </h3>
              <p class="text-[15px] text-gray-600">
                定时发布与素材管理，节奏化输出内容，并支持效果追踪（按可用性）。
              </p>
            </article>
            <article>
              <h3 class="mb-2 flex items-center space-x-2 font-medium text-gray-900">
                <svg
                  class="fill-blue-500"
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                >
                  <path d="M10.284.33a1 1 0 1 0-.574 1.917 6.049 6.049 0 0 1 2.417 1.395A1 1 0 0 0 13.5 2.188 8.034 8.034 0 0 0 10.284.33ZM6.288 2.248A1 1 0 0 0 5.718.33 8.036 8.036 0 0 0 2.5 2.187a1 1 0 0 0 1.372 1.455 6.036 6.036 0 0 1 2.415-1.395ZM1.42 5.401a1 1 0 0 1 .742 1.204 6.025 6.025 0 0 0 0 2.79 1 1 0 0 1-1.946.462 8.026 8.026 0 0 1 0-3.714A1 1 0 0 1 1.421 5.4Zm2.452 6.957A1 1 0 0 0 2.5 13.812a8.036 8.036 0 0 0 3.216 1.857 1 1 0 0 0 .574-1.916 6.044 6.044 0 0 1-2.417-1.395Zm9.668.04a1 1 0 0 1-.041 1.414 8.033 8.033 0 0 1-3.217 1.857 1 1 0 1 1-.571-1.917 6.035 6.035 0 0 0 2.415-1.395 1 1 0 0 1 1.414.042Zm2.242-6.255a1 1 0 1 0-1.946.462 6.03 6.03 0 0 1 0 2.79 1 1 0 1 0 1.946.462 8.022 8.022 0 0 0 0-3.714Z" />
                </svg>
                <span>批量触达与分发</span>
              </h3>
              <p class="text-[15px] text-gray-600">
                通过模板与策略化触达群组/频道，控制频率与范围，避免打扰。
              </p>
            </article>
            <article>
              <h3 class="mb-2 flex items-center space-x-2 font-medium text-gray-900">
                <svg
                  class="fill-blue-500"
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                >
                  <path d="M9 1a1 1 0 1 0-2 0v6a1 1 0 0 0 2 0V1ZM4.572 3.08a1 1 0 0 0-1.144-1.64A7.987 7.987 0 0 0 0 8a8 8 0 0 0 16 0c0-2.72-1.36-5.117-3.428-6.56a1 1 0 1 0-1.144 1.64A5.987 5.987 0 0 1 14 8 6 6 0 1 1 2 8a5.987 5.987 0 0 1 2.572-4.92Z" />
                </svg>
                <span>数据复盘与洞察</span>
              </h3>
              <p class="text-[15px] text-gray-600">
                汇总关键指标、对话热点与风险事件，帮助团队快速定位问题与机会。
              </p>
            </article>
          </div>
        </div>
      </div>
    </section>
</template>
